#!/bin/tcsh -v

#
# Builds the PRBEM_ADD program
#
# currently only tested using the Portland Group PGI compilers
#
# This program also requires the NSSDC/CDF library (v3.2)
# the location of which should be set in the NSSDC_CDF variable, below.
#
# H. Evans July, 2009.
#


set IRBEM_ROOT=../source
set IRBEM_LIB=oneradesp_linux_x86
set NSSDC_CDF=NSSDC_CDF
set F77=pgf77

${F77} -o prbem_add prbem_add.f \
       -I ${IRBEM_ROOT} \
       -I ${NSSDC_CDF}/include/ \
        -L ${IRBEM_ROOT} -l${IRBEM_LIB} \
        -L ${NSSDC_CDF}/lib -lcdf \
        


